version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "nest-blog-api"
# s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-y7nxqwtkpv2b"
s3_prefix = "nest-blog-api"
region = "ap-southeast-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
resolve_s3 = true
parameter_overrides = "Environment=\"production\" DatabaseUrl=\"postgresql://sk:shengzuiS3344@database-free.cl0mwk82a7up.ap-southeast-2.rds.amazonaws.com:5432/postgres?schema=public\" GitHubUsername=\"Da-Sheng\" GitHubToken=\"your_real_github_token_here\""
image_repositories = []
